### ISSUE TITLE
Mapping: Decide safe defaults for ad-hoc result materialization

### ISSUE THREAD

**Issue by JakeOverstreet** [IgnyteSoftware/inquiry#420]
## Summary

Ad-hoc DTOs bind columns by property declaration order and ignore SQL aliases. Reordering same-type SELECT expressions or DTO properties can silently assign values to the wrong properties.

## Scope

Current example:

```csharp
[InquiryAdHoc]
public sealed class PersonName
{
    public string FirstName { get; init; } = "";
    public string LastName { get; init; } = "";
}

var people = await inquiry.QueryListAsync<PersonName>(
    $"SELECT LastName, FirstName FROM People");
```

The first SQL value populates FirstName. This is source-confirmed contract behavior, not a claimed newly executed reproduction.

Recommended approach: resolve names/aliases to ordinals once per result set for handwritten queries; keep per-row generated materialization and fixed ordinals for generated SQL. Keep positional ad-hoc mapping as an explicit performance option if justified. Compare this with an explicit ordinal attribute or strict schema validation and record the tradeoff.

Do not mark a reordered name-mapped reader SequentialAccess-safe automatically. Either emit reads in ascending resolved ordinal order into locals or use the appropriate buffered path. Measure wide rows and early stream disposal; preserve the guarantee introduced by #181 where applicable.

Constructor mapping is a related convenience gap: positional records such as `[InquiryAdHoc] public sealed record PersonName(string FirstName, string LastName);` are currently rejected. Decide whether to support constructor binding now or explicitly defer it as additive work. Do not require constructor support to resolve silent misassignment.

## Acceptance criteria

- [ ] Choose name-based, explicitly positional or validated mapping semantics before the stable contract is frozen.
- [ ] Define case sensitivity, duplicate aliases, missing and extra columns, incompatible types and DBNull behavior.
- [ ] Demonstrate same-type column/property reorder behavior and useful errors for incompatible result schemas.
- [ ] Preserve or explicitly revise SequentialAccess and custom-materializer guarantees with allocation/streaming evidence.
- [ ] Document the constructor/positional-record decision and update the ad-hoc guide with safe examples.

## Evidence

Source inspection at commit `4678d8f70cea274180469ff239b3692047d92d09`. No new consumer execution or live-provider verification is claimed. Examples marked proposed are design sketches, not supported syntax.

[docs/site/articles/features/ad-hoc-dtos.md](https://github.com/IgnyteSoftware/inquiry/blob/4678d8f70cea274180469ff239b3692047d92d09/docs/site/articles/features/ad-hoc-dtos.md)

[src/Inquiry.Generators.Shared/AdHocProcessor.cs](https://github.com/IgnyteSoftware/inquiry/blob/4678d8f70cea274180469ff239b3692047d92d09/src/Inquiry.Generators.Shared/AdHocProcessor.cs)

[src/Inquiry/IInquiry.cs](https://github.com/IgnyteSoftware/inquiry/blob/4678d8f70cea274180469ff239b3692047d92d09/src/Inquiry/IInquiry.cs)

## Release decision

Milestone: **1.0.0**. Settle this public contract or complete the scoped documentation before stable API freeze. A decision issue may close with an explicit acceptance or deferral; proposed syntax is not an implementation commitment.

## Related work

- #181
- #423
